import 'package:sign_language/models/OptionModel.dart';

List<OptionModel> familyList = [
  OptionModel(title: "اطفال", image: "assets/images/family/اطفال.png"),
  OptionModel(title: "اعضا", image: "assets/images/family/اعضا.png"),
  OptionModel(title: "اقارب", image: "assets/images/family/اقارب.png"),
  OptionModel(title: "بابا", image: "assets/images/family/بابا.png"),
  OptionModel(title: "برادر", image: "assets/images/family/برادر.png"),
  OptionModel(
      title: "برادر زاده", image: "assets/images/family/برادر زاده.png"),
  OptionModel(title: "بیوه", image: "assets/images/family/بیوه.png"),
  OptionModel(title: "خاله", image: "assets/images/family/خاله.png"),
  OptionModel(title: "خانم(زن)", image: "assets/images/family/خانم(زن).png"),
  OptionModel(title: "خسر", image: "assets/images/family/خسر.png"),
  OptionModel(title: "خسربره", image: "assets/images/family/خسربره.png"),
  OptionModel(title: "خشو", image: "assets/images/family/خشو.png"),
  OptionModel(title: "خواهر", image: "assets/images/family/خواهر.png"),
  OptionModel(title: "خواهر", image: "assets/images/family/خواهر.png"),
  OptionModel(title: "خواهرزاده", image: "assets/images/family/خواهرزاده.png"),
  OptionModel(title: "خیاشنه", image: "assets/images/family/خیاشنه.png"),
  OptionModel(title: "داماد", image: "assets/images/family/داماد.png"),
  OptionModel(title: "دختر", image: "assets/images/family/دختر.png"),
  OptionModel(title: "دخترم", image: "assets/images/family/دخترم.png"),
  OptionModel(title: "دوگانگی", image: "assets/images/family/دوگانگی.png"),
  OptionModel(title: "زن", image: "assets/images/family/زن.png"),
  OptionModel(title: "شوهر", image: "assets/images/family/شوهر.png"),
  OptionModel(title: "طفل", image: "assets/images/family/طفل.png"),
  OptionModel(
      title: "طفل شیر خوار", image: "assets/images/family/طفل شیر خوار.png"),
  OptionModel(title: "طفل پسر", image: "assets/images/family/طفل پسر.png"),
  OptionModel(title: "عروس", image: "assets/images/family/عروس.png"),
  OptionModel(title: "فامیل", image: "assets/images/family/فامیل.png"),
  OptionModel(title: "مادر", image: "assets/images/family/مادر.png"),
  OptionModel(title: "مادر کلان", image: "assets/images/family/مادر کلان.png"),
  OptionModel(title: "ماما", image: "assets/images/family/ماما.png"),
  OptionModel(title: "مجرد", image: "assets/images/family/مجرد.png"),
  OptionModel(
      title: "مرد(مذکر) ", image: "assets/images/family/مرد(مذکر) .png"),
  OptionModel(title: "نامزد", image: "assets/images/family/نامزد.png"),
  OptionModel(title: "نامزد شدن", image: "assets/images/family/نامزد شدن.png"),
  OptionModel(title: "همباق", image: "assets/images/family/همباق.png"),
  OptionModel(title: "والدین", image: "assets/images/family/والدین.png"),
  OptionModel(title: "پدر", image: "assets/images/family/پدر.png"),
  OptionModel(title: "پدر کلان", image: "assets/images/family/پدر کلان.png"),
  OptionModel(title: "پسرم", image: "assets/images/family/پسرم.png"),
  OptionModel(title: "کاکا", image: "assets/images/family/کاکا.png"),
];
